name: "Autofill_daily_temperature"

on:
  schedule:
    - cron: "0 2 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run sign
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python3 main.py